### ISSUE TITLE
[Cypress] - Better result reporting

### ISSUE THREAD

**Issue by juadk** [epinio/epinio-end-to-end-tests#144]
Until now, results are only available when you go to Github Action and check the Cypress run step.
Maybe we can export the result as an HTLM page and make it easier to find/read.

**Comment by mmartin24** [comment]
Made progress using this pluging:
`npm i mochawesome`

It creates an artifact with screenshots and videos when tests fails.

Local results:

https://user-images.githubusercontent.com/37271841/192831213-27cbd68b-34f3-4cd7-aa6f-ea85f195c7cc.mov



However it seems to have an issue in [ci](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3144991786) finding the right paths:
![image](https://user-images.githubusercontent.com/37271841/192830692-1608067a-5b64-4c52-b1ae-b0bc2109df45.png)

Will continue working on a solution.

**Comment by mmartin24** [comment]
Managed to copy screenshots and videos within `mochawesome-report` directory and read the artifact from there:
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3177952134

![image](https://user-images.githubusercontent.com/37271841/193701376-20fa67ab-d057-414f-a5fa-ed7181673ed2.png)
I will polish this tomorrow

**Comment by mmartin24** [comment]
I will finally merge the artifact approach here: https://github.com/epinio/epinio-end-to-end-tests/pull/237
As a summary this this approach, as explained above, creates an artifact with copies of videos and screenshots but also:
- It always displays the videos (even if succeeds and 
- It displays screenshots if fails.
- It creates 1 html page per runner.

This is how it looks: [mochawesome-report-light.zip](https://github.com/epinio/epinio-end-to-end-tests/files/9734864/mochawesome-report-light.zip)
![image](https://user-images.githubusercontent.com/37271841/194581648-557cafa2-e2a7-43a6-a22e-1d40ab0dd21c.png)

And here the new artifact on CI:
![image](https://user-images.githubusercontent.com/37271841/194582664-0ac5f66e-7ca0-4210-96b1-ba29cdf16d28.png)

I tried to merge all pages into one using this approach: https://medium.com/swlh/publish-your-cypress-test-report-with-github-actions-47248788713a 
This worked well when tests are not parallelized, but since we do it overrides all the time the html generated on each test. We can always revisit this issue in the future
Furthermore, it can also be revisited the attempt to change directly the report on the own gh action page with the use of `peaceiris/actions-gh-pages@v3`
